In [ ]:
# default_exp radom_forest

# codecentric.AI Bootcamp - Random Forests

## Aufgaben

Hier findet ihr eine Reihe von Übungsaufgaben zu Random Forests.

Folge den Aufgaben und ergänze die ___ in den Code-Abschnitten.

Die folgenden Pakete werden geladen:

In [ ]:
#hide
from nbdev.showdoc import *

In [ ]:
%matplotlib inline

In [ ]:
#export
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

### Aufgabe 1: Datensätze aus Scikit-learn laden

Für die nachfolgenden Übungsaufgaben wollen wir zwei Datensätze verwenden, einen für Klassifikationsmodelle und einen anderen für Regressionsmodelle.

- Importiere die Funktion zum Laden des `iris` Datensatzes.
- Importiere die Funktion zum Laden des `boston` Datensatzes.

In [ ]:
#export
# Irisdaten für Klassifikation
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import confusion_matrix

- Lade den `iris` Datensatz ohne weitere Argumente anzugeben und gucke dir die Beschreibung an.

In [ ]:
#export
data_iris = load_iris()
print(data_iris.DESCR)

.. _iris_dataset:

Iris plants dataset
--------------------

**Data Set Characteristics:**

    :Number of Instances: 150 (50 in each of three classes)
    :Number of Attributes: 4 numeric, predictive attributes and the class
    :Attribute Information:
        - sepal length in cm
        - sepal width in cm
        - petal length in cm
        - petal width in cm
        - class:
                - Iris-Setosa
                - Iris-Versicolour
                - Iris-Virginica
                
    :Summary Statistics:

    ============== ==== ==== ======= ===== ====================
                    Min  Max   Mean    SD   Class Correlation
    ============== ==== ==== ======= ===== ====================
    sepal length:   4.3  7.9   5.84   0.83    0.7826
    sepal width:    2.0  4.4   3.05   0.43   -0.4194
    petal length:   1.0  6.9   3.76   1.76    0.9490  (high!)
    petal width:    0.1  2.5   1.20   0.76    0.9565  (high!)
    ============== ==== ==== ======= ===== ===========

- Lade den `iris` Datensatz so, dass du zwei einzelne Objekte zurück bekommst: einen für die Featurewerte und einen für die Antwortvariable.

In [ ]:
#export
features_iris, target_iris = load_iris(return_X_y=True)

### Aufgabe 2: Daten mit Scikit-learn in Trainings- und Testsets aufteilen

Nun wollen wir die beiden Datensätze, die wir geladen haben, in Trainings- und Testsets aufteilen.

- Importiere die entsprechene Funktion für das Aufteilen der Datensätze aus Scikit-learn.

- Teile die Feature und Targets des `iris` Datensatzes in zwei Sets ein: 80% der Daten sollen in das Trainingsset, 20% in das Testset. 
- Stratifiziere die Aufteilung anhand der Antwortvariablen.

In [ ]:
#export

X_train_iris, X_test_iris, y_train_iris, y_test_iris = train_test_split(
    features_iris,
    target_iris,
    test_size=0.2,
    stratify=target_iris,
    random_state = 42)

### Aufgabe 3: Klassifikation mit Random Forests in Scikit-learn

Nun sind unsere `iris` Daten bereit für das Trainieren von Modellen.

- Importiere den Random Forest Klassifikationsalgorithmus.
- Definiere den Random Forest Algorithmus mit den folgenden Hyperparametern: 200 Bäume mit maximaler Tiefe von 3. maximaler Anzahl in Betracht zu ziehender Feature von 3 und aktiviere Out-Of-Bag Sampling.
- Trainiere das so definierte Modell auf den `iris` Trainingsdaten.

In [ ]:
#export

rf_model_class = RandomForestClassifier(
    n_estimators=200, 
    max_depth=3,
    max_features=3,
    bootstrap=True,
    random_state = 42)
rf_model_class.fit(X_train_iris, y_train_iris)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=3, max_features=3, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=200, n_jobs=None,
            oob_score=False, random_state=42, verbose=0, warm_start=False)

- Importiere die Funktion zur Erstellung von Kreuzmatrizen aus Scikit-learn.
- Nutze das Random Forest Klassifikationsmodell um Vorhersagen auf den Testdaten zu machen.
- Vergleiche die vorhergesagten Klassen mit den tatsächlichen Klassen des Testsets, indem du die Kreuzmatrix ausgeben lässt.

In [ ]:
#export

y_pred_rf_class = rf_model_class.predict(X_test_iris)

print(confusion_matrix(y_test_iris, y_pred_rf_class, labels=np.unique(y_test_iris)))

[[10  0  0]
 [ 0  9  1]
 [ 0  0 10]]
